// Generated by CoffeeScript 1.3.1
var language, o, page_layout, render, render_function, table_tr, tr_template;

render = (require('./json2page')).json2page;

o = console.log;

page_layout = function(table, title) {
  var template;
  template = {
    $html: {
      $head: {
        $title: title,
        $meta: {
          charset: 'utf-8'
        },
        $style: {
          body: {
            margin: 0
          },
          '*': {
            'font-size': 13,
            'line-height': 22,
            'font-family': 'wenquanyi micro hei, arial'
          },
          td: {
            padding: '20px 10px',
            'min-width': 500,
            'vertical-align': 'top',
            'text-align': 'top'
          },
          tr: {
            background: '#fff'
          },
          'tr:nth-child(2n)': {
            background: '#CEDAC1'
          },
          table: {
            border: 0,
            width: '100%',
            'border-collapse': 'collapse'
          },
          code: {
            'font-family': 'wenquanyi micro hei mono, monospace'
          },
          'td>code': {
            background: '#211',
            color: '#eef',
            padding: '1px 3px',
            margin: '1px 1px'
          },
          pre: {
            margin: 0,
            'font-family': 'wenquanyi micro hei mono, monospace'
          },
          a: {
            'text-decoration': 'none',
            color: '#3737D5'
          }
        }
      },
      $body: {
        $table: table
      }
    }
  };
  return render(template);
};

language = '';

tr_template = function(codes, notes) {
  var html;
  html = {
    $tr: {
      $td1: {
        $pre: {
          $code: {
            "class": language,
            $page: codes
          }
        }
      },
      $td2: {
        $page: notes
      }
    }
  };
  return render(html);
};

table_tr = function(arr) {
  var codes, line, notes, _i, _len;
  codes = [];
  notes = [];
  for (_i = 0, _len = arr.length; _i < _len; _i++) {
    line = arr[_i];
    line = line.replace(/</g, '&lt;').replace(/>/g, '&gt;');
    if (line.match(/^\s\s/)) {
      codes.push(line);
    } else {
      notes.push(line);
    }
  }
  codes = codes.map(function(line) {
    return line = line.slice(2);
  });
  codes = codes.join('\n');
  notes = notes.map(function(line) {
    return line = line.replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/`([^`]*[^\\`]+)`/g, '<code>$1</code>').replace(/(https?:(\/\/)?(\S+))/g, '<a href="$1">$3</a>').replace(/#([^\\\S]+)#/g, '<b>$1</b>');
  });
  notes = notes.join('<br>');
  return tr_template(codes, notes);
};

render_function = function(file_string, title, lang) {
  var cut_lines, differ, i, last_cut, lines, mark, tr_tags, _i, _len, _ref,
    _this = this;
  language = lang;
  tr_tags = '';
  last_cut = -1;
  lines = file_string.split('\n');
  lines = lines.filter(function(line) {
    var p;
    p = line.match(/^\s*$/);
    if (p != null) {
      return false;
    } else {
      return true;
    }
  });
  cut_lines = function(index) {
    tr_tags += table_tr(lines.slice(last_cut + 1, index + 1 || 9e9));
    return last_cut = index;
  };
  differ = lines.map(function(line) {
    if ((line.match(/^\s\s+/)) != null) {
      return 'c';
    } else {
      return 'note';
    }
  });
  _ref = differ.slice(0, -1);
  for (i = _i = 0, _len = _ref.length; _i < _len; i = ++_i) {
    mark = _ref[i];
    if (mark === 'note' && differ[i + 1] === 'c') {
      cut_lines(i);
    }
  }
  cut_lines(lines.length - 1);
  return page_layout(tr_tags, title);
};

/*
fs = require 'fs'
fs.readFile 'text', 'utf-8', (err, data) ->
  throw err if err
  o render_function data, 'my title', 'CoffeeScript'
*/


if (exports) {
  exports.render = render_function;
}
